name: clima
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: '>=3.2.0-0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #cupertino_icons: ^0.1.2
  cupertino_icons: ^1.0.6
  geolocator: ^7.0.0
  http: ^0.13.4
  permission_handler: ^8.2.5
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Spartan MB
      fonts:
        - asset: fonts/SpartanMB-Black.otf
          weight: 900